name: Build and Push Docker Image

on:
    workflow_run:
      workflows: ["Python application", "Snyk Test"]  # Trigger this workflow after successful completion of the others
      types:
        - completed

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker image
        env:
          CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG=ghcr.io/hs-heilbronn-devsecops-universe/note-api:$COMMIT_SHA

          docker build -t $IMAGE_TAG -t ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest .

          echo $CONTAINER_TOKEN | docker login ghcr.io -u hs-heilbronn-devsecops-universe --password-stdin

          docker push $IMAGE_TAG
          docker push ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest
