name: Build and Push Image

on: workflow_call

jobs:
  # dependent on snyk-test
  build-and-push-image:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker image
      env:
        CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
      run: |
        # Generate a unique tag based on the current Git commit SHA
        COMMIT_SHA=$(git rev-parse --short HEAD)
        IMAGE_TAG=ghcr.io/hs-heilbronn-devsecops-universe/note-api:$COMMIT_SHA

        # Build the Docker image with the unique tag and also tag it as latest
        docker build -t $IMAGE_TAG -t ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest .

        # Log in to the GitHub Container Registry
        echo $CONTAINER_TOKEN | docker login ghcr.io -u hs-heilbronn-devsecops-universe --password-stdin

        # Push both tags to the registry
        docker push $IMAGE_TAG
        docker push ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest