name: Main Workflow

on:
  push:

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:

  job1:
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit

  job2:
    needs: job1
    uses: ./.github/workflows/security-tests.yml
    secrets: inherit

  job3:
    needs: job2
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

  job4:
    needs: job3
    uses: ./.github/workflows/deploy-image.yml
    secrets: inherit
