# This workflow will install Python dependencies, run tests, and lint with a single version of Python.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  

permissions:
  contents: read
  actions: read                 # Allows reading actions and workflows
  security-events: write        # Allows uploading SARIF files
  id-token: write  # Allow id toke write


jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    # Uncomment the following lines to enable linting
    # - name: Lint with flake8
    #   run: |
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with coverage (optional)
      run: |
        # Run tests with coverage in parallel, provide feedback immediately
        pytest --cov=note_api --cov-report=term --cov-report=xml --maxfail=5 -n auto
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: false


  snyk-test:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/main'      #if merge request to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
  
  # dependent on snyk-test
  build-and-push-image:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [snyk-test, lint-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker image
      env:
        CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
      run: |
        # Generate a unique tag based on the current Git commit SHA
        COMMIT_SHA=$(git rev-parse --short HEAD)
        IMAGE_TAG=ghcr.io/hs-heilbronn-devsecops-universe/note-api:$COMMIT_SHA

        # Build the Docker image with the unique tag and also tag it as latest
        docker build -t $IMAGE_TAG -t ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest .

        # Log in to the GitHub Container Registry
        echo $CONTAINER_TOKEN | docker login ghcr.io -u hs-heilbronn-devsecops-universe --password-stdin

        # Push both tags to the registry
        docker push $IMAGE_TAG
        docker push ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest

  deploy-to-cloudrun:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Pull image from GHCR and push to GCR
        env:
          CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
        run: |
          # Log in to GHCR
          echo $CONTAINER_TOKEN | docker login ghcr.io -u hs-heilbronn-devsecops-universe --password-stdin

          # Pull the latest image from GHCR
          GHCR_IMAGE=ghcr.io/hs-heilbronn-devsecops-universe/note-api:latest
          docker pull $GHCR_IMAGE

          # Tag the image for GCR
          GCR_IMAGE=europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api-repo/note-api:latest
          docker tag $GHCR_IMAGE $GCR_IMAGE

          # Push the image to GCR
          docker push $GCR_IMAGE

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: note-api-universe
          image: europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api-repo/note-api:latest
          region: europe-west3
          env_vars: BACKEND=memory