name: Snyk Test

on: workflow_call

jobs:
  snyk-test:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/main'      #if merge request to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif